# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: walkerKinematicReconstruction
channels:
- conda-forge
- default
dependencies:
- python >=3.10
- biorbd >=1.9.0
- bioviz
- pyomeca
- pyqt
- vtk
- packaging
- pytest

